name: Build container
description: ""

inputs:
  annotations:
    description: "List (new line for each entry) of annotation to set to the image"
    required: false
  build-args:
    description: "List of build-time variables"
    required: false
  dockerfile-path:
    description: "Path to the Dockerfile"
    default: "."
    required: true
  labels:
    description: "List (new line for each entry) of metadata for an image"
    required: false
  tags:
    description: "List of tags"
    required: false

outputs:
  image-id:
    description: 'Image ID'

runs:
  using: node20
  main: index.js
