name: Build container
description: ""

inputs:
  annotations:
    description: "List (new line for each entry) of annotation to set to the image"
    required: false
  build-args:
    description: "List of build-time variables"
    required: false
  dockerfile-path:
    description: "Path to the Dockerfile"
    required: false
  labels:
    description: "List (new line for each entry) of metadata for an image"
    required: false
  secrets:
    description: "List (new line for each entry) of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)"
    required: false
  tags:
    description: "List of tags"
    required: false



outputs:
  imageid:
    description: 'Image ID'
#  digest:
#    description: 'Image digest'
#  metadata:
#    description: 'Build result metadata'
#
#  container-image:
#    description: The random image name used for generation
#    value: ${{ steps.build-image.outputs.container-image }}
#  image-digest:
#    description: The digest of the final image
#    value: ${{ steps.push-image.outputs.image-digest }}

runs:
  using: node20
  main: index.js
